schema_version: 1
name: OpenArmX v10 bimanual
resources:
  driver_params: driver.yaml
  motion_params: motion_control.yaml
  sdk_config: sdk.yaml
  channel_config: channels.yaml
  tool_config: tools.yaml
  urdf: package://openarmx_description/urdf/robot/openarmx_robot.urdf
  teleop_config: teleop_vr_recv.toml
