tools:
  - name: left_tool0
    parent_frame: openarmx_left_link7
    child_frame: left_tool0
    translation_m: [0.0, 0.0, 0.1801]
    rotation_xyzw: [0.0, 0.0, 0.0, 1.0]
  - name: right_tool0
    parent_frame: openarmx_right_link7
    child_frame: right_tool0
    translation_m: [0.0, 0.0, 0.1801]
    rotation_xyzw: [0.0, 0.0, 0.0, 1.0]
